import { IHead } from 'src/@types/common';

export const TABLE_HEAD_HOP_DONG_THANH_TOAN: IHead[] = [
  {
    id: 'soHopDong',
    value: 'soHopDong',
    label: 'Số hợp đồng',
    align: 'left',
    checked: true,
    minWidth: 250,
  },
  {
    id: 'soHopDongErp',
    value: 'soHopDongErp',
    label: 'Số hợp đồng ERP',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'hopDongTramList',
    value: 'hopDongTramList',
    label: 'Số lượng trạm',
    align: 'center',
    checked: true,
    minWidth: 150,
  },
  {
    id: 'tinhTrangHopDong',
    value: 'tinhTrangHopDong',
    label: 'Tình trạng hợp đồng',
    align: 'center',
    checked: true,
    minWidth: 180,
  },
  {
    id: 'hopDongDoiTac.ten',
    value: 'hopDongDoiTac.ten',
    label: 'Tên đối tác',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'hopDongDoiTac.diaChi',
    value: 'hopDongDoiTac.diaChi',
    label: 'Địa chỉ liên hệ',
    align: 'left',
    checked: true,
    minWidth: 260,
  },
  {
    id: 'ngayKy',
    value: 'ngayKy',
    label: 'Ngày ký HĐ',
    align: 'left',
    checked: true,
    minWidth: 160,
    type: 'Date',
  },
  {
    id: 'ngayKetThuc',
    value: 'ngayKetThuc',
    label: 'Ngày kết thúc HĐ',
    align: 'left',
    checked: true,
    minWidth: 160,
    type: 'Date',
  },
  {
    id: 'hopDongDoiTac.maSoThue',
    value: 'hopDongDoiTac.maSoThue',
    label: 'Mã số thuế',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'hopDongDoiTac.cccd',
    value: 'hopDongDoiTac.cccd',
    label: 'Số CMND/CCCD',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'hopDongDoiTac.soDienThoai',
    value: 'hopDongDoiTac.soDienThoai',
    label: 'Số điện thoại',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'thueVat',
    value: 'thueVat',
    label: 'Thuế VAT',
    align: 'left',
    checked: true,
    minWidth: 160,
    format: `#value%`,
  },
  {
    id: 'chuKyTT',
    value: 'chuKyNam,chuKyThang,chuKyNgay',
    label: 'Chu kỳ thanh toán',
    align: 'left',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'hopDongDoiTac.chuTaiKhoan',
    value: 'hopDongDoiTac.chuTaiKhoan',
    label: 'Chủ tài khoản',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'hopDongDoiTac.soTaiKhoan',
    value: 'hopDongDoiTac.soTaiKhoan',
    label: 'Số tài khoản',
    align: 'left',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'hopDongDoiTac.nganHangChiNhanh',
    value: 'hopDongDoiTac.nganHangChiNhanh',
    label: 'Ngân hàng chi nhánh',
    align: 'left',
    checked: true,
    minWidth: 220,
  },
  {
    id: 'dmHinhThucThanhToan.ten',
    value: 'dmHinhThucThanhToan.ten',
    label: 'Hình thức thanh toán',
    align: 'left',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'dmDoiTuongKyHopDong.ten',
    value: 'dmDoiTuongKyHopDong.ten',
    label: 'Đối tượng ký hợp đồng',
    align: 'left',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'dmHinhThucKyHopDong.ten',
    value: 'dmHinhThucKyHopDong.ten',
    label: 'Hình thức ký hợp đồng',
    align: 'left',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'dmKhoanMuc.ma',
    value: 'dmKhoanMuc.ma',
    label: 'Khoản mục',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'ghiChu',
    value: 'ghiChu',
    label: 'Ghi chú',
    align: 'left',
    checked: true,
    minWidth: 260,
  },
  {
    id: 'createdAt',
    value: 'createdAt',
    label: 'Ngày tạo',
    align: 'left',
    checked: true,
    minWidth: 160,
    type: 'Date',
  },
  {
    id: 'updatedAt',
    value: 'updatedAt',
    label: 'Ngày cập nhật lần cuối',
    align: 'left',
    checked: true,
    minWidth: 200,
    type: 'Date',
  },
  {
    id: 'coKyQuy',
    value: 'coKyQuy',
    label: 'Ký quỹ',
    align: 'center',
    checked: true,
    minWidth: 80,
  },
  {
    id: 'giaKyQuy',
    value: 'giaKyQuy',
    label: 'Giá ký quỹ',
    align: 'center',
    checked: true,
    minWidth: 120,
    type: 'Price',
  },
  {
    id: 'hopDongPhuLucModels',
    value: 'hopDongPhuLucModels',
    label: 'Phụ lục',
    align: 'center',
    checked: true,
    minWidth: 180,
  },
];

export const HEAD_THANH_TOAN: IHead[] = [
  {
    id: 'ngayThanhToan',
    value: 'ngayThanhToan',
    label: 'Ngày thanh toán',
    align: 'left',
    checked: true,
    minWidth: 220,
    type: 'Date',
  },
];
