import { IHead, OptionTypeTram } from 'src/@types/common';

export const DRAG_TRAM_COL = 'dragColumnTram';
export const TABLE_HEAD: IHead[] = [
  { id: 'maTram', value: 'maTram', label: 'Mã trạm', align: 'left', checked: true, minWidth: 120 },
  {
    id: 'maTramErp',
    value: 'maTramErp',
    label: 'Mã trạm ERP ',
    align: 'left',
    checked: true,
    minWidth: 150,
  },
  {
    id: 'siteNameErp',
    value: 'siteNameErp',
    label: 'Site Name ERP',
    align: 'left',
    checked: true,
    minWidth: 150,
  },
  { id: 'ten', value: 'ten', label: 'Tên Trạm', align: 'left', checked: true, minWidth: 120 },
  {
    id: 'maDauTuXayDung',
    value: 'maDauTuXayDung',
    label: 'Mã ĐTXD',
    align: 'left',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'dmPhongDai',
    value: 'dmPhongDai.ten',
    label: 'Phòng/Đài',
    align: 'left',
    checked: true,
    minWidth: 140,
  },
  { id: 'dmTo', value: 'dmTo.ten', label: 'Tổ', align: 'left', checked: true, minWidth: 140 },
  {
    id: 'dmTinh',
    value: 'dmTinh.ten',
    label: 'Tỉnh/TP',
    align: 'left',
    checked: true,
    minWidth: 140,
  },
  { id: 'dmHuyen', value: 'dmHuyen.ten', label: 'Quận/Huyện', align: 'left', checked: true },
  { id: 'dmXa', value: 'dmXa.ten', label: 'Phường/Xã', align: 'left', checked: true },
  { id: 'diaChi', value: 'diaChi', label: 'Địa chỉ', align: 'left', checked: true, minWidth: 300 },
  {
    id: 'dmLoaiCotAngten',
    value: 'dmLoaiCotAngten.ten',
    label: 'Loại cột Angten',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'doCaoAngten',
    value: 'doCaoAngten',
    format: `#value (m)`,
    label: 'Độ cao Angten',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'dmLoaiCsht',
    value: 'dmLoaiCsht.ten',
    label: 'Loại CSHT',
    align: 'left',
    checked: true,
    minWidth: 180,
  },
  {
    id: 'dmLoaiTram',
    value: 'dmLoaiTram.ten',
    label: 'Loại trạm',
    align: 'left',
    checked: true,
    minWidth: 180,
  },
  {
    id: 'dmTramKhuVuc',
    value: 'dmTramKhuVuc.ten',
    label: 'Khu vực',
    align: 'left',
    checked: true,
    minWidth: 240,
  },
  { id: 'kinhDo', value: 'kinhDo', label: 'Kinh độ', align: 'left', checked: true, minWidth: 130 },
  { id: 'viDo', value: 'viDo', label: 'Vĩ độ', align: 'left', checked: true, minWidth: 130 },
  {
    id: 'ngayPhatSong',
    value: 'ngayPhatSong',
    type: 'Date',
    label: 'Ngày phát sóng',
    align: 'left',
    checked: true,
    minWidth: 160,
  },
  {
    id: 'daPhatSong',
    value: 'daPhatSong',
    label: 'Đã phát sóng',
    align: 'center',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'dmLoaiThietBiRanList',
    value: 'dmLoaiThietBiRanList',
    label: 'Loại Ran',
    align: 'center',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'trangThaiHoatDong',
    value: 'trangThaiHoatDong',
    label: 'Trạng thái',
    align: 'center',
    checked: true,
  },
  { id: 'ghiChu', value: 'ghiChu', label: 'Ghi chú', align: 'left', checked: true, minWidth: 150 },
  {
    id: 'createdAt',
    value: 'createdAt',
    type: 'Date',
    label: 'Ngày tạo',
    align: 'left',
    checked: true,
    minWidth: 140,
  },
];

export const defaultObjectFilterTram: Record<string, OptionTypeTram | null | string> = {
  tinh: null,
  huyen: null,
  xa: null,
  phongDai: null,
  to: null,
  trangThaiHoatDong: '',
  fromDate: null,
  toDate: null,
  loaiCsht: null,
};
