export const USER = [
  {
    id: 1,
    fullName: 'Nguyễn Văn A',
    email: 'nguyenvana@mobifone.vn',
    position: 'Trưởng phòng Đài',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_image.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
  {
    id: 2,
    fullName: 'Nguyễn Văn B',
    email: 'nguyenvanb@mobifone.vn',
    position: 'Phó phòng Đài',
    mobile: '0964955109',
    status: 0,
    avatar: 'ic_extra_animate.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 3,
    fullName: 'Nguyễn Thi A',
    email: 'nguyenthia@mobifone.vn',
    position: 'Phòng Vô tuyến',
    mobile: '0964955100',
    status: 0,
    avatar: 'ic_extra_carousel.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 4,
    fullName: 'Nguyễn Văn C',
    email: 'nguyenvanc@mobifone.vn',
    position: 'Phòng Vô tuyến',
    mobile: '0964955106',
    status: 1,
    avatar: 'ic_extra_chart.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
  {
    id: 5,
    fullName: 'Nguyễn Văn Vinh',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Tổ chức hành chính',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_label.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
  {
    id: 6,
    fullName: 'Phùng Quang Vinh',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Tổ chức hành chính',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_image.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
  {
    id: 7,
    fullName: 'Nguyễn Văn X',
    email: 'nguyenvana@mobifone.vn',
    position: 'Trưởng phòng Đài',
    mobile: '0964955108',
    status: 0,
    avatar: 'ic_extra_animate.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 8,
    fullName: 'Nguyễn Cao A',
    email: 'nguyenvana@mobifone.vn',
    position: 'Trưởng phòng Đài',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_carousel.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
  {
    id: 9,
    fullName: 'Nguyễn Thái A',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Kế hoạch đầu tư',
    mobile: '0964955108',
    status: 0,
    avatar: 'ic_extra_chart.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 10,
    fullName: 'Cao Văn A',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Hạ tầng',
    mobile: '0964955108',
    status: 0,
    avatar: 'ic_extra_label.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
  {
    id: 11,
    fullName: 'Trần Văn A',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Kế hoạch đầu tư',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_image.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 12,
    fullName: 'Dương Văn A',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Kế Toán',
    mobile: '0964955108',
    status: 0,
    avatar: 'ic_extra_animate.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 13,
    fullName: 'Nguyễn Văn Dương',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Kế Toán',
    mobile: '0964955108',
    status: 0,
    avatar: 'ic_extra_carousel.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 14,
    fullName: 'Nguyễn Văn Amm',
    email: 'nguyenvana@mobifone.vn',
    position: 'Phòng Tổ chức hành chính',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_chart.png',
    stations: [],
    gender: 'nu',
    group: '10010',
  },
  {
    id: 15,
    fullName: 'Nguyễn In Out',
    email: 'nguyenvana@mobifone.vn',
    position: 'Tổ xét thầu',
    mobile: '0964955108',
    status: 1,
    avatar: 'ic_extra_label.png',
    stations: [],
    gender: 'nam',
    group: '10010',
  },
];

export const OPTIONS_ROLE = [
  { value: 'all', label: 'Tất cả' },
  { value: 'active', label: 'Đang hoạt động' },
  { value: 'inactive', label: 'Ngừng hoạt động' },
];

export const TABLE_HEAD = [
  { id: 'fullName', label: 'Tên đầy đủ', align: 'left' },
  { id: 'email', label: 'Email', align: 'left', width: 250 },
  { id: 'position', label: 'Chức vụ', align: 'left', width: 150 },
  { id: 'mobile', label: 'Số điện thoại', align: 'left', width: 150 },
  { id: 'status', label: 'Trạng thái', align: 'left', width: 180 },
  { id: 'action', label: '', align: 'right', width: 50 },
];

export const PHAN_QUYEN = [
  {
    key: 'nguoiDung',
    label: 'Quản lý người dùng',
    child: [
      { label: 'Xem', checked: true, key: 'READ' },
      { label: 'Thêm mới', checked: true, key: 'CREATE' },
      { label: 'Cập nhật', checked: true, key: 'UPDATE' },
    ],
  },
  {
    key: 'chucVu',
    label: 'Quản lý chức vụ',
    child: [
      { label: 'Xem', checked: true, key: 'READ' },
      { label: 'Thêm mới', checked: true, key: 'CREATE' },
      { label: 'Cập nhật', checked: true, key: 'UPDATE' },
    ],
  },
  {
    key: 'danhMuc',
    label: 'Danh mục',
    child: [
      { label: 'Xem', checked: true, key: 'READ' },
      { label: 'Thêm mới', checked: true, key: 'CREATE' },
      { label: 'Cập nhật', checked: true, key: 'UPDATE' },
      { label: 'Import', checked: true, key: 'IMPORT' },
    ],
  },
  {
    key: 'tram',
    label: 'TRẠm',
    child: [
      { label: 'Xem', checked: true, key: 'READ' },
      { label: 'Thêm mới', checked: true, key: 'CREATE' },
      { label: 'Cập nhật', checked: true, key: 'UPDATE' },
      { label: 'Import', checked: true, key: 'IMPORT' },
    ],
  },
  {
    key: 'hopDong',
    label: 'Hợp đồng',
    child: [
      { label: 'Xem', checked: true, key: 'READ' },
      { label: 'Thêm mới', checked: true, key: 'CREATE' },
      { label: 'Cập nhật', checked: true, key: 'UPDATE' },
      { label: 'Import', checked: true, key: 'IMPORT' },
      { label: 'Xét duyệt', checked: true, key: 'IMPROVE' },
    ],
  },
  { key: 'baoCao', label: 'Báo cáo', child: [{ label: 'Xem', checked: true, key: 'READ' }] },
];

const array: string[] = [];
PHAN_QUYEN.forEach((item) => {
  item.child.forEach((itemChild) => {
    array.push(`${item.key}_${itemChild.key}`);
  });
});

export const listKeyChecked = array;

export const CHUC_VU = [
  { id: 1, value: 'Trưởng phòng Đài' },
  { id: 2, value: 'Phó phòng Đài' },
  { id: 3, value: 'Tổ xét thầu' },
  { id: 4, value: 'Phòng Tổ chức hành chính' },
  { id: 5, value: 'Phòng Kế Toán' },
  { id: 6, value: 'Phòng Kế hoạch đầu tư' },
  { id: 7, value: 'Phòng Hạ tầng' },
  { id: 8, value: 'Phòng Vô tuyến' },
  { id: 9, value: 'Phòng Truyền dẫn' },
];
