export const STATIONS = [
  {
    id: 1,
    stationCode: 'H01051',
    stationCodeERP: '00023181',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 1,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 2,
    stationCode: 'H01052',
    stationCodeERP: null,
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 0,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 3,
    stationCode: 'H01053',
    stationCodeERP: '00023182',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 2,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 4,
    stationCode: 'H01054',
    stationCodeERP: '00023183',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 1,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 5,
    stationCode: 'H01055',
    stationCodeERP: '00023184',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 2,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 6,
    stationCode: 'H01056',
    stationCodeERP: null,
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 0,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 7,
    stationCode: 'H01057',
    stationCodeERP: '00023185',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 1,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 8,
    stationCode: 'H01058',
    stationCodeERP: '00023186',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 1,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 9,
    stationCode: 'H01059',
    stationCodeERP: '00023187',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 0,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 10,
    stationCode: 'H01050',
    stationCodeERP: '00023188',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 2,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 11,
    stationCode: 'H01011',
    stationCodeERP: '00023189',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 2,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 12,
    stationCode: 'H01012',
    stationCodeERP: '00023180',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 0,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 13,
    stationCode: 'H01013',
    stationCodeERP: '00023190',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 0,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 14,
    stationCode: 'H01014',
    stationCodeERP: '00023191',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 1,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 1,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 15,
    stationCode: 'H01015',
    stationCodeERP: '00023123',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 1,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
  {
    id: 16,
    stationCode: 'H01015',
    stationCodeERP: '00023123',
    stationName: '07 NAM QUỐC CANG',
    province: 'TPHCM',
    district: 'Q.01',
    ward: 'Phường Phạm Ngũ Lão',
    address: '07 Nam Quốc Cang, Phường Phạm Ngũ Lão, Q.01, TPHCM',
    lat: '105.1234E',
    long: '21.0021N',
    broadcastStatus: 2,
    dateTime: '2023-04-03 00:00:00',
    typeCSHT: 'Indoor',
    teleRoom: 'ĐVTT',
    group: 'VT4',
    area: 'Vùng đặc biệt',
    typeStation: 'trạm trên mái',
    typeRAN: '4G',
    typeAnten: 'CS Monopole 30m',
    antenHeight: 30,
    activeStatus: 0,
    note: 'avcdfđfdđ',
    numberContract: 2,
    totalContract: 10,
    createdAt: '2023-01-04 00:00:00',
    updatedAt: '2023-04-03 23:59:59',
  },
];

export const showColumn = [
  {
    id: 'stationCode',
    label: 'Mã trạm',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'stationCodeERP',
    label: 'Mã trạm ERP',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'stationName',
    label: 'Tên trạm',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'province',
    label: 'Tỉnh/TP',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'district',
    label: 'Quận/Huyện',
    checked: true,
    minWidth: 120,
  },
  {
    id: 'ward',
    label: 'Phường/Xã',
    checked: true,
    minWidth: 200,
  },
  {
    id: 'address',
    label: 'Địa chỉ trạm',
    checked: false,
    minWidth: 200,
  },
  {
    id: 'lat',
    label: 'Kinh độ',
    checked: false,
    minWidth: 120,
  },
  {
    id: 'long',
    label: 'Vĩ độ',
    checked: false,
    minWidth: 130,
  },
  {
    id: 'broadcastStatus',
    label: 'Trạng thái PS',
    checked: true,
    minWidth: 130,
    description: 'Trạng thái phát sóng',
  },
  {
    id: 'dateTime',
    label: 'Ngày phát sóng',
    checked: true,
    minWidth: 130,
  },
  {
    id: 'typeCSHT',
    label: 'Loại CSHT',
    checked: false,
    minWidth: 120,
  },
  {
    id: 'teleRoom',
    label: 'Phòng đài',
    checked: false,
    minWidth: 100,
  },
  {
    id: 'group',
    label: 'Tổ',
    checked: false,
    minWidth: 80,
  },
  {
    id: 'area',
    label: 'Khu vực',
    checked: false,
    minWidth: 120,
  },
  {
    id: 'typeStation',
    label: 'Loại trạm',
    checked: false,
    minWidth: 120,
  },
  {
    id: 'typeRAN',
    label: 'Loại TB RAN',
    checked: false,
    minWidth: 80,
    description: 'Loại thiết bị RAN',
  },
  {
    id: 'typeAnten',
    label: 'Loại cột anten',
    checked: false,
    minWidth: 150,
  },
  {
    id: 'antenHeight',
    label: 'ĐC anten',
    checked: false,
    minWidth: 80,
    description: 'Độ cao cột anten (tính bằng met)',
  },
  {
    id: 'activeStatus',
    label: 'T.thái HĐ',
    checked: true,
    minWidth: 100,
    description: 'Trạng thái hoạt động',
  },
  {
    id: 'note',
    label: 'Ghi chú',
    checked: false,
    minWidth: 150,
  },
  {
    id: 'numberContract',
    label: 'Số HĐĐTT',
    checked: false,
    minWidth: 80,
    description: 'Số hợp đồng đang thực thi',
  },
  {
    id: 'totalContract',
    label: 'Tổng số HĐ',
    checked: false,
    minWidth: 80,
    description: 'Tổng số hợp đồng',
  },
  {
    id: 'createdAt',
    label: 'Ngày tạo',
    checked: false,
    minWidth: 120,
  },
  {
    id: 'updatedAt',
    label: 'Ngày cập nhật',
    checked: false,
    minWidth: 120,
    description: 'Ngày cập nhật lần cuối',
  },
];

export const STATION_STATUS = [
  { label: 'Tất cả', value: 'all' },
  { label: 'Đã phát sóng', value: 'broadcasted' },
  { label: 'Chưa phát sóng', value: 'notBroadcasted' },
  { label: 'Pending', value: 'pending' },
];

export const ACTIVE_STATUS = [
  { label: 'Tất cả', value: 'all' },
  { label: 'Tạm dừng', value: 'pending' },
  { label: 'Hoạt động', value: 'active' },
];
